// 'hello','owu','com', 'ua', 1, 10, -999, 123, 3.14, 2.7, 16, true, false.
let z1 = 'hello';
let z2 = 'owu';
let z3 = 'com';
let z4 = 'ua';
let z5 = 1;
let z6 = 10;
let z7 = -999;
let z8 = 123;
let z9 = 3.14;
let z10 = 2.7;
let z11 = 16;
let z12 = true;
let z13 = false;
let firstName = 'Vitalii';
let middleName = 'Petrovich';
let lastName = 'Fedychkanych';
let space = ' ';
let a = 100;
let b = '100';
let c = true;
console.log(z1);
console.log(z2);
console.log(z3);
console.log(z4);
console.log(z5);
console.log(z6);
console.log(z7);
console.log(z8);
console.log(z9);
console.log(z10);
console.log(z11);
console.log(z12);
console.log(z13);
console.log(firstName+space+middleName+space+lastName);
console.log(typeof a);
console.log(typeof b);
console.log(typeof c);
const name = prompt('Як Вас звати?', '');
const yourMiddleName = prompt('Як Вас по-батькові?', '');
const age = prompt('Скільки вам років?', '');
console.log('Привіт '+name+' '+yourMiddleName+' , вам '+age+' років !')
